// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xenogears.Database;

namespace Xenogears.Database.Migrations
{
    [DbContext(typeof(XenogearsDBContext))]
    [Migration("20210101000916_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Xenogears.Database.XGCharacter", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Name = "Fei"
                        },
                        new
                        {
                            Name = "Elly"
                        },
                        new
                        {
                            Name = "Citan"
                        },
                        new
                        {
                            Name = "Bart"
                        },
                        new
                        {
                            Name = "Billy"
                        },
                        new
                        {
                            Name = "Rico"
                        },
                        new
                        {
                            Name = "Esmeralda"
                        },
                        new
                        {
                            Name = "Chu-Chu"
                        },
                        new
                        {
                            Name = "Maria"
                        },
                        new
                        {
                            Name = "Adult Esmeralda"
                        });
                });

            modelBuilder.Entity("Xenogears.Database.XGCharacterAnimation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CharacterName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkipBetweenFiles")
                        .HasColumnType("int");

                    b.Property<string>("StartSprite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterName");

                    b.ToTable("CharacterAnimations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterName = "Fei",
                            Count = 1,
                            Name = "Idle",
                            SkipBetweenFiles = 0,
                            StartSprite = "FieldPCSprites2\\003922_bin\\0000.png"
                        },
                        new
                        {
                            Id = 2,
                            CharacterName = "Fei",
                            Count = 8,
                            Name = "Walk",
                            SkipBetweenFiles = 0,
                            StartSprite = "FieldPCSprites1\\000427_bin\\0025.png"
                        },
                        new
                        {
                            Id = 3,
                            CharacterName = "Fei",
                            Count = 8,
                            Name = "Run",
                            SkipBetweenFiles = 0,
                            StartSprite = "FieldPCSprites1\\000427_bin\\0065.png"
                        },
                        new
                        {
                            Id = 4,
                            CharacterName = "Fei",
                            Count = 8,
                            Name = "Jump",
                            SkipBetweenFiles = 0,
                            StartSprite = "FieldPCSprites1\\000427_bin\\0105.png"
                        },
                        new
                        {
                            Id = 5,
                            CharacterName = "Fei",
                            Count = 4,
                            Name = "Climb",
                            SkipBetweenFiles = 0,
                            StartSprite = "FieldPCSprites1\\000427_bin\\0005.png"
                        },
                        new
                        {
                            Id = 6,
                            CharacterName = "Fei",
                            Count = 4,
                            Name = "Action1",
                            SkipBetweenFiles = 7,
                            StartSprite = "FieldPCSprites1\\000427_bin\\0145.png"
                        },
                        new
                        {
                            Id = 7,
                            CharacterName = "Fei",
                            Count = 3,
                            Name = "Action2",
                            SkipBetweenFiles = 8,
                            StartSprite = "FieldPCSprites1\\000427_bin\\0149.png"
                        },
                        new
                        {
                            Id = 8,
                            CharacterName = "Fei",
                            Count = 4,
                            Name = "Action3",
                            SkipBetweenFiles = 7,
                            StartSprite = "FieldPCSprites1\\000427_bin\\0152.png"
                        },
                        new
                        {
                            Id = 9,
                            CharacterName = "Elly",
                            Count = 1,
                            Name = "Idle",
                            SkipBetweenFiles = 3,
                            StartSprite = "FieldPCSprites2\\003923_bin\\0003.png"
                        },
                        new
                        {
                            Id = 10,
                            CharacterName = "Elly",
                            Count = 8,
                            Name = "Walk",
                            SkipBetweenFiles = 0,
                            StartSprite = "FieldPCSprites1\\000428_bin\\0055.png"
                        },
                        new
                        {
                            Id = 11,
                            CharacterName = "Elly",
                            Count = 8,
                            Name = "Run",
                            SkipBetweenFiles = 0,
                            StartSprite = "FieldPCSprites1\\000428_bin\\0150.png"
                        },
                        new
                        {
                            Id = 12,
                            CharacterName = "Elly",
                            Count = 6,
                            Name = "Jump",
                            SkipBetweenFiles = 0,
                            StartSprite = "FieldPCSprites1\\000428_bin\\0000.png"
                        },
                        new
                        {
                            Id = 13,
                            CharacterName = "Elly",
                            Count = 3,
                            Name = "Action1",
                            SkipBetweenFiles = 1,
                            StartSprite = "FieldPCSprites2\\003923_bin\\0000.png"
                        },
                        new
                        {
                            Id = 14,
                            CharacterName = "Citan",
                            Count = 1,
                            Name = "Idle",
                            SkipBetweenFiles = 0,
                            StartSprite = "FieldPCSprites2\\003923_bin\\0040.png"
                        },
                        new
                        {
                            Id = 15,
                            CharacterName = "Citan",
                            Count = 8,
                            Name = "Walk",
                            SkipBetweenFiles = 6,
                            StartSprite = "FieldPCSprites1\\000429_bin\\0120.png"
                        },
                        new
                        {
                            Id = 16,
                            CharacterName = "Citan",
                            Count = 8,
                            Name = "Run",
                            SkipBetweenFiles = 0,
                            StartSprite = "FieldPCSprites1\\000429_bin\\0060.png"
                        },
                        new
                        {
                            Id = 17,
                            CharacterName = "Citan",
                            Count = 6,
                            Name = "Jump",
                            SkipBetweenFiles = 0,
                            StartSprite = "FieldPCSprites1\\000429_bin\\0000.png"
                        },
                        new
                        {
                            Id = 18,
                            CharacterName = "Citan",
                            Count = 4,
                            Name = "Climb",
                            SkipBetweenFiles = 0,
                            StartSprite = "FieldPCSprites1\\000429_bin\\0100.png"
                        },
                        new
                        {
                            Id = 19,
                            CharacterName = "Citan",
                            Count = 4,
                            Name = "Action1",
                            SkipBetweenFiles = 0,
                            StartSprite = "FieldPCSprites1\\000429_bin\\0040.png"
                        },
                        new
                        {
                            Id = 20,
                            CharacterName = "Citan",
                            Count = 6,
                            Name = "Action2",
                            SkipBetweenFiles = 8,
                            StartSprite = "FieldPCSprites1\\000429_bin\\0128.png"
                        });
                });

            modelBuilder.Entity("Xenogears.Database.XGCharacterAnimation", b =>
                {
                    b.HasOne("Xenogears.Database.XGCharacter", null)
                        .WithMany("RawAnimationsData")
                        .HasForeignKey("CharacterName");
                });

            modelBuilder.Entity("Xenogears.Database.XGCharacter", b =>
                {
                    b.Navigation("RawAnimationsData");
                });
#pragma warning restore 612, 618
        }
    }
}
